/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 12
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  sym_label = 4,
  sym_opcode = 5,
  sym_illegal = 6,
  sym_control = 7,
  sym_data = 8,
  sym_math = 9,
  sym_file = 10,
  sym_threed = 11,
  sym_storage = 12,
  sym_object = 13,
  sym_function = 14,
  sym_preprocessor = 15,
  sym_program = 16,
  sym_block = 17,
  sym_statement = 18,
  sym_inst = 19,
  aux_sym_program_repeat1 = 20,
  aux_sym_block_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_label] = "label",
  [sym_opcode] = "opcode",
  [sym_illegal] = "illegal",
  [sym_control] = "control",
  [sym_data] = "data",
  [sym_math] = "math",
  [sym_file] = "file",
  [sym_threed] = "threed",
  [sym_storage] = "storage",
  [sym_object] = "object",
  [sym_function] = "function",
  [sym_preprocessor] = "preprocessor",
  [sym_program] = "program",
  [sym_block] = "block",
  [sym_statement] = "statement",
  [sym_inst] = "inst",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_label] = sym_label,
  [sym_opcode] = sym_opcode,
  [sym_illegal] = sym_illegal,
  [sym_control] = sym_control,
  [sym_data] = sym_data,
  [sym_math] = sym_math,
  [sym_file] = sym_file,
  [sym_threed] = sym_threed,
  [sym_storage] = sym_storage,
  [sym_object] = sym_object,
  [sym_function] = sym_function,
  [sym_preprocessor] = sym_preprocessor,
  [sym_program] = sym_program,
  [sym_block] = sym_block,
  [sym_statement] = sym_statement,
  [sym_inst] = sym_inst,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_opcode] = {
    .visible = true,
    .named = true,
  },
  [sym_illegal] = {
    .visible = true,
    .named = true,
  },
  [sym_control] = {
    .visible = true,
    .named = true,
  },
  [sym_data] = {
    .visible = true,
    .named = true,
  },
  [sym_math] = {
    .visible = true,
    .named = true,
  },
  [sym_file] = {
    .visible = true,
    .named = true,
  },
  [sym_threed] = {
    .visible = true,
    .named = true,
  },
  [sym_storage] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_preprocessor] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_inst] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(268);
      ADVANCE_MAP(
        '.', 185,
        '/', 1,
        'A', 125,
        'C', 142,
        'E', 151,
        'H', 143,
        'I', 6,
        'L', 80,
        'M', 14,
        'P', 37,
        'R', 12,
        'S', 27,
        'T', 127,
        'V', 38,
        'a', 13,
        'c', 26,
        'e', 118,
        'f', 65,
        'h', 122,
        'i', 148,
        'l', 82,
        'm', 16,
        'p', 83,
        'r', 11,
        's', 54,
        't', 3,
        '{', 270,
        '}', 271,
        0x212a, 230,
        'B', 132,
        'b', 132,
        'D', 133,
        'd', 133,
        'J', 128,
        'j', 128,
        'K', 141,
        'k', 141,
        'N', 149,
        'n', 149,
        'O', 131,
        'o', 131,
        'X', 126,
        'x', 126,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '!' ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 1:
      if (lookahead == '/') ADVANCE(269);
      END_STATE();
    case 2:
      if (lookahead == '1') ADVANCE(283);
      if (lookahead == ':') ADVANCE(272);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        ':', 272,
        'A', 159,
        'O', 152,
        'a', 73,
        'o', 5,
        'S', 164,
        's', 164,
        'X', 167,
        'x', 167,
        'Y', 130,
        'y', 130,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'B') ADVANCE(60);
      if (lookahead == 'P') ADVANCE(61);
      if (lookahead == 'S') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'D') ADVANCE(43);
      if (lookahead == 'R') ADVANCE(21);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'E') ADVANCE(7);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(160);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(174);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'E') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'E') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'F') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'M') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 11:
      ADVANCE_MAP(
        ':', 272,
        'O', 172,
        'a', 77,
        'o', 114,
        'L', 129,
        'l', 129,
        'R', 129,
        'r', 129,
        'T', 171,
        't', 171,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 12:
      ADVANCE_MAP(
        ':', 272,
        'O', 172,
        'o', 107,
        'L', 129,
        'l', 129,
        'R', 129,
        'r', 129,
        'T', 171,
        't', 171,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 13:
      ADVANCE_MAP(
        ':', 272,
        'S', 145,
        'T', 163,
        'b', 102,
        'c', 81,
        's', 53,
        't', 19,
        'A', 170,
        'a', 170,
        'D', 135,
        'd', 135,
        'L', 156,
        'l', 156,
        'N', 136,
        'n', 136,
        'R', 156,
        'r', 156,
        'X', 166,
        'x', 166,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('e' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 14:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'a') ADVANCE(108);
      if (lookahead == 'o') ADVANCE(116);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 15:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'a') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 16:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'a') ADVANCE(119);
      if (lookahead == 'i') ADVANCE(72);
      if (lookahead == 'o') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 17:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'a') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 18:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'a') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 19:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'a') ADVANCE(75);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 20:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'a') ADVANCE(110);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 21:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'a') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 22:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'a') ADVANCE(109);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 23:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'a') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 24:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'a') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 25:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'a') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 26:
      ADVANCE_MAP(
        ':', 272,
        'b', 97,
        'e', 56,
        'o', 103,
        'r', 47,
        'L', 182,
        'l', 182,
        'M', 153,
        'm', 153,
        'P', 176,
        'p', 176,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 27:
      ADVANCE_MAP(
        ':', 272,
        'c', 17,
        0x212a, 267,
        'A', 175,
        'a', 175,
        'B', 134,
        'b', 134,
        'E', 179,
        'e', 179,
        'H', 180,
        'h', 180,
        'K', 168,
        'k', 168,
        'L', 150,
        'l', 150,
        'R', 138,
        'r', 138,
        'T', 177,
        't', 177,
        'X', 129,
        'x', 129,
        'Y', 129,
        'y', 129,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('C' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('d' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 28:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'c') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 29:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'c') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 30:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'c') ADVANCE(111);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 31:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'd') ADVANCE(283);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 32:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'd') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 33:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'd') ADVANCE(284);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 34:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'd') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 35:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'd') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 36:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'd') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 37:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'e') ADVANCE(98);
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(165);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(165);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 38:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'e') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 39:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'e') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 40:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'e') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 41:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'e') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 42:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'e') ADVANCE(284);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 43:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'e') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 44:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'e') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 45:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'e') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 46:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'e') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 47:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'e') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 48:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'e') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 49:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'g') ADVANCE(279);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 50:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'g') ADVANCE(76);
      if (lookahead == 'n') ADVANCE(281);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 51:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'g') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 52:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'i') ADVANCE(116);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 53:
      ADVANCE_MAP(
        ':', 272,
        'i', 72,
        'L', 273,
        'l', 273,
        'O', 275,
        'R', 275,
        'o', 275,
        'r', 275,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 54:
      ADVANCE_MAP(
        ':', 272,
        'i', 50,
        'q', 97,
        0x212a, 267,
        'A', 175,
        'a', 175,
        'B', 134,
        'b', 134,
        'E', 179,
        'e', 179,
        'H', 180,
        'h', 180,
        'K', 168,
        'k', 168,
        'L', 150,
        'l', 150,
        'R', 138,
        'r', 138,
        'T', 177,
        't', 177,
        'X', 129,
        'x', 129,
        'Y', 129,
        'y', 129,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('C' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('c' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 55:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'i') ADVANCE(120);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 56:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'i') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 57:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'i') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 58:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'i') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 59:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'i') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 60:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'i') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 61:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'i') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 62:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'i') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 63:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'i') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 64:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'l') ADVANCE(283);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 65:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'l') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 66:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'l') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 67:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'l') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 68:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'm') ADVANCE(283);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 69:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'm') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 70:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'n') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 71:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'n') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 72:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'n') ADVANCE(283);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 73:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'n') ADVANCE(281);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(275);
      if (lookahead == 'X' ||
          lookahead == 'Y' ||
          lookahead == 'x' ||
          lookahead == 'y') ADVANCE(273);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 74:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'n') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 75:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'n') ADVANCE(280);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 76:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'n') ADVANCE(113);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 77:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'n') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 78:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'n') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 79:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'n') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 80:
      ADVANCE_MAP(
        ':', 272,
        'o', 18,
        'A', 181,
        'a', 181,
        'D', 177,
        'd', 177,
        'S', 137,
        's', 137,
        'X', 129,
        'x', 129,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 81:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'o') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 82:
      ADVANCE_MAP(
        ':', 272,
        'o', 49,
        'A', 181,
        'a', 181,
        'D', 177,
        'd', 177,
        'S', 137,
        's', 137,
        'X', 129,
        'x', 129,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 83:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'o') ADVANCE(117);
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(165);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(165);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 84:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'o') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 85:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'o') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 86:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'o') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 87:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'o') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 88:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'o') ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 89:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'o') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 90:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'p') ADVANCE(282);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 91:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'p') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 92:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'p') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 93:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'r') ADVANCE(283);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 94:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'r') ADVANCE(285);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 95:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'r') ADVANCE(121);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 96:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'r') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 97:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'r') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 98:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'r') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 99:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'r') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 100:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'r') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 101:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'r') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 102:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 's') ADVANCE(283);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 103:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 's') ADVANCE(281);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 104:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 's') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 105:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 't') ADVANCE(283);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 106:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 't') ADVANCE(115);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 107:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 't') ADVANCE(20);
      if (lookahead == 'L' ||
          lookahead == 'R' ||
          lookahead == 'l' ||
          lookahead == 'r') ADVANCE(273);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 108:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 't') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 109:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 't') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 110:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 't') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 111:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 't') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 112:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 't') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 113:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'u') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 114:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'u') ADVANCE(71);
      if (lookahead == 'L' ||
          lookahead == 'R' ||
          lookahead == 'l' ||
          lookahead == 'r') ADVANCE(273);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 115:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'u') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 116:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'v') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 117:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'w') ADVANCE(283);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 118:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'x') ADVANCE(90);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(157);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 119:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'x') ADVANCE(283);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 120:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'x') ADVANCE(285);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 121:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'y') ADVANCE(284);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 122:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'y') ADVANCE(91);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(161);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 123:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 0x212a) ADVANCE(276);
      if (lookahead == 'K' ||
          lookahead == 'k') ADVANCE(277);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 124:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == '0' ||
          lookahead == 'p') ADVANCE(283);
      if (('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 125:
      ADVANCE_MAP(
        ':', 272,
        'A', 170,
        'a', 170,
        'D', 135,
        'd', 135,
        'L', 156,
        'l', 156,
        'N', 136,
        'n', 136,
        'R', 156,
        'r', 156,
        'S', 145,
        's', 145,
        'T', 163,
        't', 163,
        'X', 166,
        'x', 166,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 126:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(166);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 127:
      ADVANCE_MAP(
        ':', 272,
        'A', 159,
        'a', 159,
        'O', 152,
        'o', 152,
        'S', 164,
        's', 164,
        'X', 167,
        'x', 167,
        'Y', 130,
        'y', 130,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 128:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(147);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(154);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(158);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 129:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 130:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(273);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 131:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(144);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(130);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 132:
      ADVANCE_MAP(
        ':', 272,
        'C', 169,
        'c', 169,
        'E', 155,
        'e', 155,
        'I', 162,
        'i', 162,
        'M', 140,
        'm', 140,
        'N', 139,
        'n', 139,
        'P', 146,
        'p', 146,
        'R', 123,
        'r', 123,
        'V', 169,
        'v', 169,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 133:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(173);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(178);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(152);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 134:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(273);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 135:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(273);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 136:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(273);
      if (('C' <= lookahead && lookahead <= 'E') ||
          ('c' <= lookahead && lookahead <= 'e')) ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 137:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(275);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(273);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 138:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 139:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(277);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 140:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(277);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 141:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 142:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(182);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(153);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 143:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(161);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 144:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 145:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(273);
      if (lookahead == 'O' ||
          lookahead == 'R' ||
          lookahead == 'o' ||
          lookahead == 'r') ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 146:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(277);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 147:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 148:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(160);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(174);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 149:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(153);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 150:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 151:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(157);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 152:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 153:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(273);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 154:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(277);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 155:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'Q' ||
          lookahead == 'q') ADVANCE(277);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 156:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 157:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(273);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 158:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(277);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 159:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(275);
      if (lookahead == 'X' ||
          lookahead == 'Y' ||
          lookahead == 'x' ||
          lookahead == 'y') ADVANCE(273);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 160:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(275);
      if (lookahead == 'C' ||
          lookahead == 'X' ||
          lookahead == 'Y' ||
          lookahead == 'c' ||
          lookahead == 'x' ||
          lookahead == 'y') ADVANCE(273);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 161:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 162:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(273);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 163:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 164:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(273);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 165:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'A' ||
          lookahead == 'P' ||
          lookahead == 'a' ||
          lookahead == 'p') ADVANCE(273);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 166:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'A' ||
          lookahead == 'S' ||
          lookahead == 'a' ||
          lookahead == 's') ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 167:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'A' ||
          lookahead == 'S' ||
          lookahead == 'a' ||
          lookahead == 's') ADVANCE(273);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 168:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'B' ||
          lookahead == 'W' ||
          lookahead == 'b' ||
          lookahead == 'w') ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 169:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'C' ||
          lookahead == 'S' ||
          lookahead == 'c' ||
          lookahead == 's') ADVANCE(277);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 170:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'C' ||
          lookahead == 'X' ||
          lookahead == 'c' ||
          lookahead == 'x') ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 171:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'I' ||
          lookahead == 'S' ||
          lookahead == 'i' ||
          lookahead == 's') ADVANCE(277);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 172:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'L' ||
          lookahead == 'R' ||
          lookahead == 'l' ||
          lookahead == 'r') ADVANCE(273);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 173:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'M' ||
          lookahead == 'P' ||
          lookahead == 'm' ||
          lookahead == 'p') ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 174:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'B' ||
          lookahead == 'C' ||
          lookahead == 'b' ||
          lookahead == 'c') ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 175:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'X' ||
          lookahead == 'Y' ||
          lookahead == 'x' ||
          lookahead == 'y') ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 176:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'X' ||
          lookahead == 'Y' ||
          lookahead == 'x' ||
          lookahead == 'y') ADVANCE(273);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 177:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'A' ||
          lookahead == 'X' ||
          lookahead == 'Y' ||
          lookahead == 'a' ||
          lookahead == 'x' ||
          lookahead == 'y') ADVANCE(273);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 178:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'C' ||
          lookahead == 'X' ||
          lookahead == 'Y' ||
          lookahead == 'c' ||
          lookahead == 'x' ||
          lookahead == 'y') ADVANCE(273);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 179:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'C' ||
          lookahead == 'D' ||
          lookahead == 'I' ||
          lookahead == 'c' ||
          lookahead == 'd' ||
          lookahead == 'i') ADVANCE(273);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 180:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'A' ||
          lookahead == 'S' ||
          lookahead == 'X' ||
          lookahead == 'Y' ||
          lookahead == 'a' ||
          lookahead == 's' ||
          lookahead == 'x' ||
          lookahead == 'y') ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 181:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'E' ||
          lookahead == 'R' ||
          lookahead == 'S' ||
          lookahead == 'X' ||
          lookahead == 'e' ||
          lookahead == 'r' ||
          lookahead == 's' ||
          lookahead == 'x') ADVANCE(275);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 182:
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'C' ||
          lookahead == 'D' ||
          lookahead == 'I' ||
          lookahead == 'V' ||
          lookahead == 'c' ||
          lookahead == 'd' ||
          lookahead == 'i' ||
          lookahead == 'v') ADVANCE(273);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 183:
      if (lookahead == ':') ADVANCE(272);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 184:
      if (lookahead == 'A') ADVANCE(231);
      if (lookahead == 'a') ADVANCE(186);
      END_STATE();
    case 185:
      ADVANCE_MAP(
        'E', 236,
        'I', 234,
        'P', 219,
        'a', 199,
        'e', 192,
        'f', 195,
        'i', 187,
        'p', 209,
        'B', 266,
        'b', 266,
        'C', 240,
        'c', 240,
        'D', 264,
        'd', 264,
        'L', 214,
        'l', 214,
        'R', 228,
        'r', 228,
        'S', 253,
        's', 253,
        'T', 225,
        't', 225,
        'V', 216,
        'v', 216,
        'W', 243,
        'w', 243,
      );
      END_STATE();
    case 186:
      if (lookahead == 'L') ADVANCE(292);
      if (lookahead == 'l') ADVANCE(288);
      END_STATE();
    case 187:
      if (lookahead == 'M') ADVANCE(246);
      if (lookahead == 'm') ADVANCE(189);
      END_STATE();
    case 188:
      if (lookahead == 'O') ADVANCE(251);
      if (lookahead == 'o') ADVANCE(190);
      END_STATE();
    case 189:
      if (lookahead == 'P') ADVANCE(244);
      if (lookahead == 'p') ADVANCE(188);
      END_STATE();
    case 190:
      if (lookahead == 'R') ADVANCE(259);
      if (lookahead == 'r') ADVANCE(191);
      END_STATE();
    case 191:
      if (lookahead == 'T') ADVANCE(242);
      if (lookahead == 't') ADVANCE(291);
      END_STATE();
    case 192:
      if (lookahead == 'V') ADVANCE(215);
      if (lookahead == 'r') ADVANCE(206);
      if (lookahead == 'v') ADVANCE(184);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(261);
      END_STATE();
    case 193:
      if (lookahead == 'e') ADVANCE(208);
      END_STATE();
    case 194:
      if (lookahead == 'g') ADVANCE(201);
      END_STATE();
    case 195:
      if (lookahead == 'i') ADVANCE(200);
      END_STATE();
    case 196:
      if (lookahead == 'i') ADVANCE(194);
      END_STATE();
    case 197:
      if (lookahead == 'i') ADVANCE(202);
      END_STATE();
    case 198:
      if (lookahead == 'l') ADVANCE(288);
      END_STATE();
    case 199:
      if (lookahead == 'l') ADVANCE(196);
      if (lookahead == 's') ADVANCE(210);
      END_STATE();
    case 200:
      if (lookahead == 'l') ADVANCE(198);
      END_STATE();
    case 201:
      if (lookahead == 'n') ADVANCE(288);
      END_STATE();
    case 202:
      if (lookahead == 'n') ADVANCE(211);
      END_STATE();
    case 203:
      if (lookahead == 'o') ADVANCE(213);
      END_STATE();
    case 204:
      if (lookahead == 'o') ADVANCE(207);
      END_STATE();
    case 205:
      if (lookahead == 'r') ADVANCE(206);
      END_STATE();
    case 206:
      if (lookahead == 'r') ADVANCE(204);
      END_STATE();
    case 207:
      if (lookahead == 'r') ADVANCE(288);
      END_STATE();
    case 208:
      if (lookahead == 'r') ADVANCE(212);
      END_STATE();
    case 209:
      if (lookahead == 'r') ADVANCE(197);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(292);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(227);
      END_STATE();
    case 210:
      if (lookahead == 's') ADVANCE(193);
      END_STATE();
    case 211:
      if (lookahead == 't') ADVANCE(290);
      END_STATE();
    case 212:
      if (lookahead == 't') ADVANCE(289);
      END_STATE();
    case 213:
      if (lookahead == 'w') ADVANCE(288);
      END_STATE();
    case 214:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(217);
      END_STATE();
    case 215:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(231);
      END_STATE();
    case 216:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(247);
      END_STATE();
    case 217:
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(229);
      END_STATE();
    case 218:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(292);
      END_STATE();
    case 219:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(292);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(227);
      END_STATE();
    case 220:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(224);
      END_STATE();
    case 221:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(255);
      END_STATE();
    case 222:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(278);
      END_STATE();
    case 223:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(241);
      END_STATE();
    case 224:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(292);
      END_STATE();
    case 225:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(265);
      END_STATE();
    case 226:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(278);
      END_STATE();
    case 227:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(262);
      END_STATE();
    case 228:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(257);
      END_STATE();
    case 229:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(233);
      END_STATE();
    case 230:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(232);
      END_STATE();
    case 231:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(292);
      END_STATE();
    case 232:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(274);
      END_STATE();
    case 233:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(286);
      END_STATE();
    case 234:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(246);
      END_STATE();
    case 235:
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(287);
      END_STATE();
    case 236:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(261);
      if (lookahead == 'V' ||
          lookahead == 'v') ADVANCE(215);
      END_STATE();
    case 237:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(292);
      END_STATE();
    case 238:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(252);
      END_STATE();
    case 239:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(220);
      END_STATE();
    case 240:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(238);
      END_STATE();
    case 241:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(245);
      END_STATE();
    case 242:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(239);
      END_STATE();
    case 243:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(248);
      END_STATE();
    case 244:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(251);
      END_STATE();
    case 245:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(218);
      END_STATE();
    case 246:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(244);
      END_STATE();
    case 247:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(286);
      END_STATE();
    case 248:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(222);
      END_STATE();
    case 249:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(237);
      END_STATE();
    case 250:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(260);
      END_STATE();
    case 251:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(259);
      END_STATE();
    case 252:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(254);
      END_STATE();
    case 253:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(250);
      END_STATE();
    case 254:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(286);
      END_STATE();
    case 255:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(287);
      END_STATE();
    case 256:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(278);
      END_STATE();
    case 257:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(263);
      END_STATE();
    case 258:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(226);
      END_STATE();
    case 259:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(242);
      END_STATE();
    case 260:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(221);
      END_STATE();
    case 261:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(235);
      END_STATE();
    case 262:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(223);
      END_STATE();
    case 263:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(249);
      END_STATE();
    case 264:
      if (lookahead == 'W' ||
          lookahead == 'w') ADVANCE(243);
      END_STATE();
    case 265:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(256);
      END_STATE();
    case 266:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(258);
      END_STATE();
    case 267:
      if (lookahead == 'B' ||
          lookahead == 'W' ||
          lookahead == 'b' ||
          lookahead == 'w') ADVANCE(274);
      END_STATE();
    case 268:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 269:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(269);
      END_STATE();
    case 270:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 271:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 272:
      ACCEPT_TOKEN(sym_label);
      END_STATE();
    case 273:
      ACCEPT_TOKEN(sym_opcode);
      if (lookahead == ':') ADVANCE(272);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 274:
      ACCEPT_TOKEN(sym_illegal);
      END_STATE();
    case 275:
      ACCEPT_TOKEN(sym_illegal);
      if (lookahead == ':') ADVANCE(272);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 276:
      ACCEPT_TOKEN(sym_control);
      END_STATE();
    case 277:
      ACCEPT_TOKEN(sym_control);
      if (lookahead == ':') ADVANCE(272);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 278:
      ACCEPT_TOKEN(sym_data);
      END_STATE();
    case 279:
      ACCEPT_TOKEN(sym_math);
      if (lookahead == '1') ADVANCE(124);
      if (lookahead == ':') ADVANCE(272);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 280:
      ACCEPT_TOKEN(sym_math);
      if (lookahead == '2') ADVANCE(283);
      if (lookahead == ':') ADVANCE(272);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 281:
      ACCEPT_TOKEN(sym_math);
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'h') ADVANCE(283);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 282:
      ACCEPT_TOKEN(sym_math);
      if (lookahead == ':') ADVANCE(272);
      if (lookahead == 'm') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 283:
      ACCEPT_TOKEN(sym_math);
      if (lookahead == ':') ADVANCE(272);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 284:
      ACCEPT_TOKEN(sym_file);
      if (lookahead == ':') ADVANCE(272);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 285:
      ACCEPT_TOKEN(sym_threed);
      if (lookahead == ':') ADVANCE(272);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(183);
      END_STATE();
    case 286:
      ACCEPT_TOKEN(sym_storage);
      END_STATE();
    case 287:
      ACCEPT_TOKEN(sym_object);
      END_STATE();
    case 288:
      ACCEPT_TOKEN(sym_function);
      END_STATE();
    case 289:
      ACCEPT_TOKEN(sym_function);
      if (lookahead == 'e') ADVANCE(205);
      END_STATE();
    case 290:
      ACCEPT_TOKEN(sym_function);
      if (lookahead == 'n') ADVANCE(203);
      END_STATE();
    case 291:
      ACCEPT_TOKEN(sym_function);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(239);
      END_STATE();
    case 292:
      ACCEPT_TOKEN(sym_preprocessor);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_label] = ACTIONS(1),
    [sym_opcode] = ACTIONS(1),
    [sym_illegal] = ACTIONS(1),
    [sym_control] = ACTIONS(1),
    [sym_data] = ACTIONS(1),
    [sym_math] = ACTIONS(1),
    [sym_file] = ACTIONS(1),
    [sym_threed] = ACTIONS(1),
    [sym_storage] = ACTIONS(1),
    [sym_object] = ACTIONS(1),
    [sym_function] = ACTIONS(1),
    [sym_preprocessor] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_program] = STATE(11),
    [sym_block] = STATE(7),
    [sym_statement] = STATE(3),
    [sym_inst] = STATE(7),
    [aux_sym_program_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_label] = ACTIONS(9),
    [sym_opcode] = ACTIONS(11),
    [sym_illegal] = ACTIONS(11),
    [sym_control] = ACTIONS(11),
    [sym_data] = ACTIONS(13),
    [sym_math] = ACTIONS(11),
    [sym_file] = ACTIONS(11),
    [sym_threed] = ACTIONS(11),
    [sym_storage] = ACTIONS(13),
    [sym_object] = ACTIONS(13),
    [sym_function] = ACTIONS(11),
    [sym_preprocessor] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_block] = STATE(7),
    [sym_statement] = STATE(4),
    [sym_inst] = STATE(7),
    [aux_sym_block_repeat1] = STATE(4),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(15),
    [sym_label] = ACTIONS(9),
    [sym_opcode] = ACTIONS(11),
    [sym_illegal] = ACTIONS(11),
    [sym_control] = ACTIONS(11),
    [sym_data] = ACTIONS(13),
    [sym_math] = ACTIONS(11),
    [sym_file] = ACTIONS(11),
    [sym_threed] = ACTIONS(11),
    [sym_storage] = ACTIONS(13),
    [sym_object] = ACTIONS(13),
    [sym_function] = ACTIONS(11),
    [sym_preprocessor] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym_block] = STATE(7),
    [sym_statement] = STATE(5),
    [sym_inst] = STATE(7),
    [aux_sym_program_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(7),
    [sym_label] = ACTIONS(9),
    [sym_opcode] = ACTIONS(11),
    [sym_illegal] = ACTIONS(11),
    [sym_control] = ACTIONS(11),
    [sym_data] = ACTIONS(13),
    [sym_math] = ACTIONS(11),
    [sym_file] = ACTIONS(11),
    [sym_threed] = ACTIONS(11),
    [sym_storage] = ACTIONS(13),
    [sym_object] = ACTIONS(13),
    [sym_function] = ACTIONS(11),
    [sym_preprocessor] = ACTIONS(11),
  },
  [STATE(4)] = {
    [sym_block] = STATE(7),
    [sym_statement] = STATE(6),
    [sym_inst] = STATE(7),
    [aux_sym_block_repeat1] = STATE(6),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(19),
    [sym_label] = ACTIONS(9),
    [sym_opcode] = ACTIONS(11),
    [sym_illegal] = ACTIONS(11),
    [sym_control] = ACTIONS(11),
    [sym_data] = ACTIONS(13),
    [sym_math] = ACTIONS(11),
    [sym_file] = ACTIONS(11),
    [sym_threed] = ACTIONS(11),
    [sym_storage] = ACTIONS(13),
    [sym_object] = ACTIONS(13),
    [sym_function] = ACTIONS(11),
    [sym_preprocessor] = ACTIONS(11),
  },
  [STATE(5)] = {
    [sym_block] = STATE(7),
    [sym_statement] = STATE(5),
    [sym_inst] = STATE(7),
    [aux_sym_program_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(23),
    [sym_label] = ACTIONS(26),
    [sym_opcode] = ACTIONS(29),
    [sym_illegal] = ACTIONS(29),
    [sym_control] = ACTIONS(29),
    [sym_data] = ACTIONS(32),
    [sym_math] = ACTIONS(29),
    [sym_file] = ACTIONS(29),
    [sym_threed] = ACTIONS(29),
    [sym_storage] = ACTIONS(32),
    [sym_object] = ACTIONS(32),
    [sym_function] = ACTIONS(29),
    [sym_preprocessor] = ACTIONS(29),
  },
  [STATE(6)] = {
    [sym_block] = STATE(7),
    [sym_statement] = STATE(6),
    [sym_inst] = STATE(7),
    [aux_sym_block_repeat1] = STATE(6),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(35),
    [anon_sym_RBRACE] = ACTIONS(38),
    [sym_label] = ACTIONS(40),
    [sym_opcode] = ACTIONS(43),
    [sym_illegal] = ACTIONS(43),
    [sym_control] = ACTIONS(43),
    [sym_data] = ACTIONS(46),
    [sym_math] = ACTIONS(43),
    [sym_file] = ACTIONS(43),
    [sym_threed] = ACTIONS(43),
    [sym_storage] = ACTIONS(46),
    [sym_object] = ACTIONS(46),
    [sym_function] = ACTIONS(43),
    [sym_preprocessor] = ACTIONS(43),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(49),
    [anon_sym_RBRACE] = ACTIONS(49),
    [sym_label] = ACTIONS(49),
    [sym_opcode] = ACTIONS(51),
    [sym_illegal] = ACTIONS(51),
    [sym_control] = ACTIONS(51),
    [sym_data] = ACTIONS(49),
    [sym_math] = ACTIONS(51),
    [sym_file] = ACTIONS(51),
    [sym_threed] = ACTIONS(51),
    [sym_storage] = ACTIONS(49),
    [sym_object] = ACTIONS(49),
    [sym_function] = ACTIONS(51),
    [sym_preprocessor] = ACTIONS(51),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(53),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(53),
    [anon_sym_RBRACE] = ACTIONS(53),
    [sym_label] = ACTIONS(53),
    [sym_opcode] = ACTIONS(55),
    [sym_illegal] = ACTIONS(55),
    [sym_control] = ACTIONS(55),
    [sym_data] = ACTIONS(53),
    [sym_math] = ACTIONS(55),
    [sym_file] = ACTIONS(55),
    [sym_threed] = ACTIONS(55),
    [sym_storage] = ACTIONS(53),
    [sym_object] = ACTIONS(53),
    [sym_function] = ACTIONS(55),
    [sym_preprocessor] = ACTIONS(55),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(57),
    [anon_sym_RBRACE] = ACTIONS(57),
    [sym_label] = ACTIONS(57),
    [sym_opcode] = ACTIONS(59),
    [sym_illegal] = ACTIONS(59),
    [sym_control] = ACTIONS(59),
    [sym_data] = ACTIONS(57),
    [sym_math] = ACTIONS(59),
    [sym_file] = ACTIONS(59),
    [sym_threed] = ACTIONS(59),
    [sym_storage] = ACTIONS(57),
    [sym_object] = ACTIONS(57),
    [sym_function] = ACTIONS(59),
    [sym_preprocessor] = ACTIONS(59),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(61),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(61),
    [anon_sym_RBRACE] = ACTIONS(61),
    [sym_label] = ACTIONS(61),
    [sym_opcode] = ACTIONS(63),
    [sym_illegal] = ACTIONS(63),
    [sym_control] = ACTIONS(63),
    [sym_data] = ACTIONS(61),
    [sym_math] = ACTIONS(63),
    [sym_file] = ACTIONS(63),
    [sym_threed] = ACTIONS(63),
    [sym_storage] = ACTIONS(61),
    [sym_object] = ACTIONS(61),
    [sym_function] = ACTIONS(63),
    [sym_preprocessor] = ACTIONS(63),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inst, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inst, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_kickassembler(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "kickassembler",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 3,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
